# Generated by Django 2.2.10 on 2020-02-11 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itam_app', '0002_auto_20200210_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='os_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_type', to='itam_app.Os_Type'),
        ),
    ]
